using System.Text;
using media_app_api.Data;
using media_app_api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

// Disable FileSystemWatcher inotify before WebApplicationBuilder constructor runs
Environment.SetEnvironmentVariable("DOTNET_USE_POLLING_FILE_WATCHER", "true");
Environment.SetEnvironmentVariable("DOTNET_CONFIGURATION_DISABLE_FILE_WATCHING", "true");

var builder = WebApplication.CreateBuilder(args);

// --- 1. Database Context ---
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");

builder.Services.AddDbContext<AppDbContext>(options =>
{
    options.UseNpgsql(connectionString, npgsqlOptions =>
    {
        npgsqlOptions.EnableRetryOnFailure(
            maxRetryCount: 5,
            maxRetryDelay: TimeSpan.FromSeconds(30),
            errorCodesToAdd: null);
    });
});

builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<ICategoryService, CategoryService>();
builder.Services.AddScoped<ICategoryGroupService, CategoryGroupService>();
builder.Services.AddScoped<IECatalogService, ECatalogService>();
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IBookingService, BookingService>();

// --- 2. JWT Authentication ---
var jwtSecret = builder.Configuration["Jwt:Secret"]
    ?? throw new InvalidOperationException("Jwt:Secret is not configured in appsettings.json or environment variables.");
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "MediaAppApi",
        ValidAudience = builder.Configuration["Jwt:Audience"] ?? "MediaAppClient",
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
        ClockSkew = TimeSpan.Zero
    };
});

builder.Services.AddAuthorization();
builder.Services.AddControllers();

// --- 3. CORS Policy for Flutter Web & Mobile ---
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFlutter", policy =>
    {
        policy.SetIsOriginAllowed(origin => true)
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
    });
});

var app = builder.Build();

// --- 4. Global Exception Handler Middleware ---
app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        context.Response.StatusCode = 500;
        context.Response.ContentType = "application/json";

        var exceptionHandlerPathFeature = context.Features.Get<IExceptionHandlerPathFeature>();
        var ex = exceptionHandlerPathFeature?.Error;

        var result = System.Text.Json.JsonSerializer.Serialize(new
        {
            message = "An unexpected error occurred on the server.",
            detail = ex?.Message
        });

        await context.Response.WriteAsync(result);
    });
});

// --- 5. Pure DDL Schema Migration (CREATE TABLE IF NOT EXISTS Only) ---
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    string migrationSql = @"
        -- 1. Create CategoryGroups table IF NOT EXISTS
        CREATE TABLE IF NOT EXISTS ""CategoryGroups"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" text NOT NULL DEFAULT '',
            ""IconName"" character varying(50) NOT NULL DEFAULT 'folder',
            CONSTRAINT ""PK_CategoryGroups"" PRIMARY KEY (""Id"")
        );

        -- 2. Create Categories table IF NOT EXISTS
        CREATE TABLE IF NOT EXISTS ""Categories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" text NOT NULL DEFAULT '',
            ""IconName"" character varying(50) NOT NULL DEFAULT 'category',
            ""CategoryGroupId"" integer NULL,
            ""ParentId"" integer NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ""PK_Categories"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Categories_CategoryGroups_CategoryGroupId"" FOREIGN KEY (""CategoryGroupId"") REFERENCES ""CategoryGroups"" (""Id"") ON DELETE SET NULL,
            CONSTRAINT ""FK_Categories_Categories_ParentId"" FOREIGN KEY (""ParentId"") REFERENCES ""Categories"" (""Id"") ON DELETE RESTRICT
        );

        -- 3. Create Products table IF NOT EXISTS
        CREATE TABLE IF NOT EXISTS ""Products"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Title"" character varying(200) NOT NULL,
            ""Price"" numeric NOT NULL DEFAULT 0,
            ""Description"" text NOT NULL DEFAULT '',
            ""ImageUrl"" text NOT NULL DEFAULT '',
            ""CategoryId"" integer NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ""PK_Products"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Products_Categories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""Categories"" (""Id"") ON DELETE SET NULL
        );

        -- 4. Create ECatalogs table IF NOT EXISTS
        CREATE TABLE IF NOT EXISTS ""ECatalogs"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Title"" character varying(255) NOT NULL,
            ""Description"" text NOT NULL DEFAULT '',
            ""CoverImageUrl"" text NOT NULL DEFAULT '',
            ""PdfUrl"" text NOT NULL DEFAULT '',
            ""CategoryGroupId"" integer NULL,
            ""CategoryId"" integer NULL,
            ""PageCount"" integer NOT NULL DEFAULT 1,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ""PK_ECatalogs"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_ECatalogs_CategoryGroups_CategoryGroupId"" FOREIGN KEY (""CategoryGroupId"") REFERENCES ""CategoryGroups"" (""Id"") ON DELETE SET NULL,
            CONSTRAINT ""FK_ECatalogs_Categories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""Categories"" (""Id"") ON DELETE SET NULL
        );

        -- 5. Guarantee Columns exist
        ALTER TABLE ""Categories"" ADD COLUMN IF NOT EXISTS ""CategoryGroupId"" integer NULL;
        ALTER TABLE ""Categories"" ADD COLUMN IF NOT EXISTS ""ParentId"" integer NULL;
    ";

    try
    {
        dbContext.Database.ExecuteSqlRaw(migrationSql);
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[Migration Warning] {ex.Message}");
    }

    dbContext.Database.EnsureCreated();
}

app.UseRouting();
app.UseCors("AllowFlutter");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
