using System.Text;
using media_app_api.Data;
using media_app_api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// --- 1. Database & Services ---
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<AppDbContext>(options =>
{
    if (connectionString != null && (connectionString.Contains("Host=") || connectionString.Contains("postgresql://")))
    {
        options.UseNpgsql(connectionString);
    }
    else
    {
        options.UseSqlServer(connectionString);
    }
});

builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<ICategoryService, CategoryService>();
builder.Services.AddScoped<IAuthService, AuthService>();

// --- 2. JWT Authentication ---
var jwtSecret = builder.Configuration["Jwt:Secret"] ?? "SuperSecretKeyForEnterpriseMediaApp2026!MustBeAtLeast32Bytes";
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "MediaAppApi",
        ValidAudience = builder.Configuration["Jwt:Audience"] ?? "MediaAppClient",
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
        ClockSkew = TimeSpan.Zero
    };
});

builder.Services.AddAuthorization();
builder.Services.AddControllers();

// --- 3. CORS Policy for Flutter Web & Mobile ---
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFlutter", policy =>
    {
        policy.SetIsOriginAllowed(origin => true)
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
    });
});

var app = builder.Build();

// --- 4. Global Exception Handler Middleware ---
app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        context.Response.StatusCode = 500;
        context.Response.ContentType = "application/json";

        var exceptionHandlerPathFeature = context.Features.Get<IExceptionHandlerPathFeature>();
        var ex = exceptionHandlerPathFeature?.Error;

        var result = System.Text.Json.JsonSerializer.Serialize(new
        {
            message = ex?.Message ?? "Internal Server Error",
            innerError = ex?.InnerException?.Message
        });

        await context.Response.WriteAsync(result);
    });
});

// --- 5. Database Schema Auto-Migration & Sequence Sync ---
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    dbContext.Database.EnsureCreated();

    var migrationSql = @"
        CREATE TABLE IF NOT EXISTS ""Categories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" character varying(500) NOT NULL DEFAULT '',
            ""IconName"" character varying(100) NOT NULL DEFAULT 'curtain',
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (now()),
            CONSTRAINT ""PK_Categories"" PRIMARY KEY (""Id"")
        );

        ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""CategoryId"" integer;
        ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""ImageUrl"" character varying(500) DEFAULT '';

        -- Synchronize PostgreSQL IDENTITY Sequences
        SELECT setval(pg_get_serial_sequence('""Products""', 'Id'), coalesce(max(""Id""), 1)) FROM ""Products"";
        SELECT setval(pg_get_serial_sequence('""Categories""', 'Id'), coalesce(max(""Id""), 1)) FROM ""Categories"";
    ";

    try
    {
        dbContext.Database.ExecuteSqlRaw(migrationSql);
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Migration log: {ex.Message}");
    }
}

// --- 6. Clean Middleware Pipeline ---
app.UseRouting();
app.UseCors("AllowFlutter");
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();
